libcomps: Use Py_hash_t instead of long in PyCOMPS_hash()
This function is used as a hashfunc callback in
_typeobject defined python3.11/cpython/object.h
compilers detect the protype mismatch for function pointers
with clang16+

Fixes
libcomps/src/python/src/pycomps_sequence.c:667:5: error: incompatible function pointer types initializing 'hashfunc' (aka 'int (*)(struct _object *)') with an expression of type 'long (*)(PyObject *)' (aka 'long (*)(struct _object *)') [-Wincompatible-function-pointer-types]
    &PyCOMPS_hash,             /*tp_hash */

Signed-off-by: Khem Raj <raj.khem@gmail.com>