Fix Python method descriptors for Python 3.8
The Python binding cannot be loaded in Python 3.8: import libcomps
fails with:

    Traceback (most recent call last):
      File "src/python/src/python3/libcomps/__init__.py", line 1, in <module>
        from ._libpycomps import *
    SystemError: bad call flags

Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1734777

The problem are the following method descriptors of
libcomps/src/python/src/pycomps.c:

    {"categories_match", (PyCFunction)PyCOMPS_categories_match, METH_KEYWORDS,
     PyCOMPS_validate__doc__},
    {"environments_match", (PyCFunction)PyCOMPS_envs_match, METH_KEYWORDS,
     PyCOMPS_validate__doc__},

In Python 3.7, import didn't check descriptor flags (METH_KEYWORDS):
these flags were only checked when the methods were called.

In Python 3.8, the flags are checked at soon as the module is
imported, which prevents the module to be imported.

This change fix the two method descriptors.